/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockRandamuVRFInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fulfillRandomness"
      | "getRandomness"
      | "isRequestFulfilled"
      | "randomnessValues"
      | "requestFulfilled"
      | "requestRandomness"
      | "resetRequest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RandomnessFulfilled" | "RandomnessRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fulfillRandomness",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestFulfilled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "randomnessValues",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFulfilled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetRequest",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRequestFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomnessValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetRequest",
    data: BytesLike
  ): Result;
}

export namespace RandomnessFulfilledEvent {
  export type InputTuple = [requestId: BigNumberish, randomness: BigNumberish];
  export type OutputTuple = [requestId: bigint, randomness: bigint];
  export interface OutputObject {
    requestId: bigint;
    randomness: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, seed: BigNumberish];
  export type OutputTuple = [requestId: bigint, seed: bigint];
  export interface OutputObject {
    requestId: bigint;
    seed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockRandamuVRF extends BaseContract {
  connect(runner?: ContractRunner | null): MockRandamuVRF;
  waitForDeployment(): Promise<this>;

  interface: MockRandamuVRFInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fulfillRandomness: TypedContractMethod<
    [requestId: BigNumberish, randomness: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRandomness: TypedContractMethod<
    [requestId: BigNumberish],
    [bigint],
    "view"
  >;

  isRequestFulfilled: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  randomnessValues: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  requestFulfilled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  requestRandomness: TypedContractMethod<
    [seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  resetRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fulfillRandomness"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomness: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRandomness"
  ): TypedContractMethod<[requestId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRequestFulfilled"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "randomnessValues"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestFulfilled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestRandomness"
  ): TypedContractMethod<[seed: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "resetRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "RandomnessFulfilled"
  ): TypedContractEvent<
    RandomnessFulfilledEvent.InputTuple,
    RandomnessFulfilledEvent.OutputTuple,
    RandomnessFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRequested"
  ): TypedContractEvent<
    RandomnessRequestedEvent.InputTuple,
    RandomnessRequestedEvent.OutputTuple,
    RandomnessRequestedEvent.OutputObject
  >;

  filters: {
    "RandomnessFulfilled(uint256,uint256)": TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;
    RandomnessFulfilled: TypedContractEvent<
      RandomnessFulfilledEvent.InputTuple,
      RandomnessFulfilledEvent.OutputTuple,
      RandomnessFulfilledEvent.OutputObject
    >;

    "RandomnessRequested(uint256,uint256)": TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
    RandomnessRequested: TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
  };
}
