/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlocklockReceiver } from "./IBlocklockReceiver";
export type { IRandamuVRF } from "./IRandamuVRF";
