/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRandamuVRFInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRandomness"
      | "isRequestFulfilled"
      | "requestRandomness"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestFulfilled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomness",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRequestFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomness",
    data: BytesLike
  ): Result;
}

export interface IRandamuVRF extends BaseContract {
  connect(runner?: ContractRunner | null): IRandamuVRF;
  waitForDeployment(): Promise<this>;

  interface: IRandamuVRFInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRandomness: TypedContractMethod<
    [requestId: BigNumberish],
    [bigint],
    "view"
  >;

  isRequestFulfilled: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  requestRandomness: TypedContractMethod<
    [seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRandomness"
  ): TypedContractMethod<[requestId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRequestFulfilled"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestRandomness"
  ): TypedContractMethod<[seed: BigNumberish], [bigint], "nonpayable">;

  filters: {};
}
