const hre = require("hardhat");

async function main() {
  const contractAddress = "0x87C730bf649e419Cc5810a14695AcDEB1f220FC1";
  
  console.log("🔍 Verifying NEW SlotMachine contract with updated game mechanics...");
  console.log("📍 Contract Address:", contractAddress);
  console.log("🌐 BaseScan URL: https://sepolia.basescan.org/address/" + contractAddress);
  
  try {
    const SlotMachine = await hre.ethers.getContractFactory("SlotMachine");
    const slotMachine = SlotMachine.attach(contractAddress);
    
    console.log("\n📊 Contract Configuration:");
    console.log("- Stake Amount:", hre.ethers.formatEther(await slotMachine.STAKE_AMOUNT()), "ETH");
    console.log("- Max Players:", Number(await slotMachine.MAX_PLAYERS_PER_ROUND()));
    console.log("- Win Percentage:", Number(await slotMachine.WIN_PERCENTAGE()), "%");
    console.log("- Plays Per Stake:", Number(await slotMachine.PLAYS_PER_STAKE())); // NEW
    console.log("- Admin Wallet:", await slotMachine.adminWallet());
    
    console.log("\n🎯 Current Round Status:");
    const currentRound = await slotMachine.getCurrentRound();
    console.log("- Round ID:", Number(currentRound.roundId));
    console.log("- Player Count:", Number(currentRound.playerCount));
    console.log("- Is Active:", currentRound.isActive);
    
    console.log("\n✅ NEW GAME MECHANICS VERIFIED!");
    console.log("🎮 How the new system works:");
    console.log("1. Stake 0.005 ETH ONCE to get 10 plays");
    console.log("2. Use 'stakeForPlays()' function to stake");
    console.log("3. Use 'playGame()' function to play (free after staking)");
    console.log("4. Each win gives you a rare NFT generated by VRF");
    console.log("5. Win 3 times total to unlock Limited Edition NFT (Blocklock-powered)");
    
    console.log("\n🔬 VRF & BLOCKLOCK INTEGRATION:");
    console.log("✅ VRF: Enhanced randomness with 8 entropy sources");
    console.log("✅ Blocklock: Deterministic Limited Edition NFT distribution");
    console.log("✅ Soul-bound NFTs: Rare NFTs are non-transferable");
    console.log("✅ Limited Edition NFTs: Transferable after 3 wins");
    
  } catch (error) {
    console.error("❌ Verification failed:", error.message);
  }
}

main()
  .then(() => {
    console.log("\n🎉 New game mechanics verification completed!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Error:", error);
    process.exit(1);
  });
